image: odinuge/maven-javafx:3-jdk-8

services:
  - mongo:latest

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Dgitlab-ci=true"
  MONGO_HOST: "mongo"

build-job:
  stage: build
  script:
    - "mvn clean compile -f tdt4140-gr1816/pom.xml $MAVEN_CLI_OPTS"

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn package -f tdt4140-gr1816/pom.xml $MAVEN_CLI_OPTS"

integrationtest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn verify -f tdt4140-gr1816/pom.xml $MAVEN_CLI_OPTS"
