---
version: '2'

services:
 mongodb:
  image: mongo:latest
  command: mongod --smallfiles --logpath=/dev/null
 api-server:
  image: gruppe16/gruppe16:latest
  environment:
   - MONGO_HOST=mongodb
  ports:
   - 8080:8080
